### ISSUE TITLE
Share your BIOS config.

### ISSUE THREAD

**Issue by Ricksonk** [psabadac/GIGABYTE-B660M-DS3H-DDR4-i7-13700F-Hackintosh-OpenCore#2]
Hello,
I've being using an adapted version of your EFI and it was working well. But right now the system isnt booting, always freezing on apple logo.
Well, I didnt update the system nor the EFI before it. Later I tried others EFI that worked before, but they arent working too, even after updating.

My question is:  Could you share your Motherboard Bios config? I think maybe that is the problem here.

I have the same config as you.

**Comment by psabadac** [comment]
Hi, 

It still works on my side. I will attach some photos from my bios.
I currently run triple boot, triple drive.
![IMG_5061](https://github.com/psabadac/GIGABYTE-B660M-DS3H-DDR4-i7-13700F-Hackintosh-OpenCore/assets/40405196/8ce56ac3-b564-45ed-b919-fb7a69ea3ecb)
![IMG_5062](https://github.com/psabadac/GIGABYTE-B660M-DS3H-DDR4-i7-13700F-Hackintosh-OpenCore/assets/40405196/ed402ee4-f15e-4116-a9c7-af5187501c8c)
![IMG_5063](https://github.com/psabadac/GIGABYTE-B660M-DS3H-DDR4-i7-13700F-Hackintosh-OpenCore/assets/40405196/ee14ba5d-608d-41e4-a74b-bae129a21619)
![IMG_5064](https://github.com/psabadac/GIGABYTE-B660M-DS3H-DDR4-i7-13700F-Hackintosh-OpenCore/assets/40405196/b5b94aff-8eb3-4e30-9d82-b58ba9b4293d)
![IMG_5065](https://github.com/psabadac/GIGABYTE-B660M-DS3H-DDR4-i7-13700F-Hackintosh-OpenCore/assets/40405196/b7be285d-1edd-42d5-9cde-7e2ae57e7653)
![IMG_5066](https://github.com/psabadac/GIGABYTE-B660M-DS3H-DDR4-i7-13700F-Hackintosh-OpenCore/assets/40405196/a41eab77-fd52-4506-aa72-20cf006ee187)
![IMG_5067](https://github.com/psabadac/GIGABYTE-B660M-DS3H-DDR4-i7-13700F-Hackintosh-OpenCore/assets/40405196/3547a5fc-6381-4904-9486-373409f7104b)
![IMG_5069](https://github.com/psabadac/GIGABYTE-B660M-DS3H-DDR4-i7-13700F-Hackintosh-OpenCore/assets/40405196/3bac8992-4b18-4ea3-b510-0d289365c3dd)

pop os, windows 10, mac os ventura.

**Comment by Ricksonk** [comment]
Hum, it is the same thing here. I really don't understand what is happening....  

But thank you for the answer, I will look for what can be done here

**Comment by psabadac** [comment]
If you have the possibility you might do a fresh install - maybe that solved the issue.
I used the linux method to download and create the usb drive and just copy-pasted the efi folder and everything works like magic.

**Comment by Ricksonk** [comment]
I've unistalled already. But I can't install again because of this problem. I though maybe it was because of the Bios config, but seems it is not. I will try to create a new EFI or maybe install Catalina and check if it works.

**Comment by Ricksonk** [comment]
Hey Petru, just to inform you, I managed to make it work  by adding 2 more files to ACPI: SSDT-RHUB.aml and SSDT-AWAC.aml. 

I cant understand why, since it was working before.

**Comment by psabadac** [comment]
Curiously B660 is NOT on the chipset list with SSDT-AWAC.aml but I am glad it worked for you.
Also SSDT-RHUB.aml - I mapped myself the USB ports so I did not had any issues with needing this one as far as I can remember.

But I am glad everything worked out for you in the end.
